
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  passwordHash: 'passwordHash',
  role: 'role',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PermissionScalarFieldEnum = {
  id: 'id',
  key: 'key',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserRoleScalarFieldEnum = {
  userId: 'userId',
  roleId: 'roleId',
  assignedAt: 'assignedAt'
};

exports.Prisma.RolePermissionScalarFieldEnum = {
  roleId: 'roleId',
  permissionId: 'permissionId'
};

exports.Prisma.LoginHistoryScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  usernameAttempt: 'usernameAttempt',
  occurredAt: 'occurredAt',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  success: 'success'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  action: 'action',
  actorUserId: 'actorUserId',
  entityType: 'entityType',
  entityId: 'entityId',
  metaJson: 'metaJson',
  ip: 'ip',
  userAgent: 'userAgent',
  createdAt: 'createdAt'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  createdAt: 'createdAt',
  expiresAt: 'expiresAt',
  lastSeenAt: 'lastSeenAt',
  userAgent: 'userAgent',
  ipAddress: 'ipAddress'
};

exports.Prisma.BranchScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  address: 'address',
  isActive: 'isActive',
  createdAt: 'createdAt'
};

exports.Prisma.PersonalTrainerScalarFieldEnum = {
  id: 'id',
  branchId: 'branchId',
  fullName: 'fullName',
  displayName: 'displayName',
  phone: 'phone',
  email: 'email',
  bio: 'bio',
  specialty: 'specialty',
  photoMediaId: 'photoMediaId',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  createdByUserId: 'createdByUserId'
};

exports.Prisma.MemberScalarFieldEnum = {
  id: 'id',
  memberCode: 'memberCode',
  branchId: 'branchId',
  firstName: 'firstName',
  lastName: 'lastName',
  email: 'email',
  phone: 'phone',
  status: 'status',
  isFrozen: 'isFrozen',
  joinedAt: 'joinedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AttendanceScalarFieldEnum = {
  id: 'id',
  memberId: 'memberId',
  branchId: 'branchId',
  membershipId: 'membershipId',
  checkInAt: 'checkInAt',
  checkOutAt: 'checkOutAt',
  source: 'source',
  memberSnapshot: 'memberSnapshot',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  memberId: 'memberId',
  membershipId: 'membershipId',
  branchId: 'branchId',
  amount: 'amount',
  currency: 'currency',
  method: 'method',
  status: 'status',
  note: 'note',
  paidAt: 'paidAt',
  createdAt: 'createdAt',
  createdByUserId: 'createdByUserId',
  deletedAt: 'deletedAt',
  deletedByUserId: 'deletedByUserId',
  voidReason: 'voidReason',
  updatedAt: 'updatedAt'
};

exports.Prisma.MembershipPlanScalarFieldEnum = {
  id: 'id',
  name: 'name',
  branchId: 'branchId',
  durationDays: 'durationDays',
  priceCents: 'priceCents',
  description: 'description',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MemberMembershipScalarFieldEnum = {
  id: 'id',
  memberId: 'memberId',
  planId: 'planId',
  branchId: 'branchId',
  startAt: 'startAt',
  endAt: 'endAt',
  cancelledAt: 'cancelledAt',
  cancelReason: 'cancelReason',
  createdAt: 'createdAt',
  createdByUserId: 'createdByUserId'
};

exports.Prisma.TagScalarFieldEnum = {
  id: 'id',
  name: 'name',
  color: 'color',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MemberTagScalarFieldEnum = {
  memberId: 'memberId',
  tagId: 'tagId',
  assignedAt: 'assignedAt'
};

exports.Prisma.MemberNoteScalarFieldEnum = {
  id: 'id',
  memberId: 'memberId',
  createdByUserId: 'createdByUserId',
  note: 'note',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MemberFlagScalarFieldEnum = {
  id: 'id',
  memberId: 'memberId',
  createdByUserId: 'createdByUserId',
  flag: 'flag',
  description: 'description',
  createdAt: 'createdAt',
  resolvedAt: 'resolvedAt'
};

exports.Prisma.MediaScalarFieldEnum = {
  id: 'id',
  memberId: 'memberId',
  branchId: 'branchId',
  kind: 'kind',
  uri: 'uri',
  mimeType: 'mimeType',
  sizeBytes: 'sizeBytes',
  createdAt: 'createdAt'
};

exports.Prisma.AppSettingScalarFieldEnum = {
  branchId: 'branchId',
  key: 'key',
  value: 'value',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SitePageScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  title: 'title',
  contentMarkdown: 'contentMarkdown',
  published: 'published',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OutboxEventScalarFieldEnum = {
  id: 'id',
  type: 'type',
  payload: 'payload',
  idempotencyKey: 'idempotencyKey',
  status: 'status',
  attempts: 'attempts',
  nextAttemptAt: 'nextAttemptAt',
  lastAttemptAt: 'lastAttemptAt',
  lastError: 'lastError',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProcessedEventScalarFieldEnum = {
  id: 'id',
  idempotencyKey: 'idempotencyKey',
  eventId: 'eventId',
  eventType: 'eventType',
  deviceId: 'deviceId',
  gymId: 'gymId',
  processedAt: 'processedAt',
  status: 'status',
  result: 'result'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.UserOrderByRelevanceFieldEnum = {
  id: 'id',
  username: 'username',
  passwordHash: 'passwordHash'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.RoleOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description'
};

exports.Prisma.PermissionOrderByRelevanceFieldEnum = {
  id: 'id',
  key: 'key',
  description: 'description'
};

exports.Prisma.UserRoleOrderByRelevanceFieldEnum = {
  userId: 'userId',
  roleId: 'roleId'
};

exports.Prisma.RolePermissionOrderByRelevanceFieldEnum = {
  roleId: 'roleId',
  permissionId: 'permissionId'
};

exports.Prisma.LoginHistoryOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  usernameAttempt: 'usernameAttempt',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.AuditLogOrderByRelevanceFieldEnum = {
  id: 'id',
  action: 'action',
  actorUserId: 'actorUserId',
  entityType: 'entityType',
  entityId: 'entityId',
  ip: 'ip',
  userAgent: 'userAgent'
};

exports.Prisma.SessionOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  userAgent: 'userAgent',
  ipAddress: 'ipAddress'
};

exports.Prisma.BranchOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  address: 'address'
};

exports.Prisma.PersonalTrainerOrderByRelevanceFieldEnum = {
  id: 'id',
  branchId: 'branchId',
  fullName: 'fullName',
  displayName: 'displayName',
  phone: 'phone',
  email: 'email',
  bio: 'bio',
  specialty: 'specialty',
  photoMediaId: 'photoMediaId',
  createdByUserId: 'createdByUserId'
};

exports.Prisma.MemberOrderByRelevanceFieldEnum = {
  id: 'id',
  memberCode: 'memberCode',
  branchId: 'branchId',
  firstName: 'firstName',
  lastName: 'lastName',
  email: 'email',
  phone: 'phone'
};

exports.Prisma.AttendanceOrderByRelevanceFieldEnum = {
  id: 'id',
  memberId: 'memberId',
  branchId: 'branchId',
  membershipId: 'membershipId'
};

exports.Prisma.PaymentOrderByRelevanceFieldEnum = {
  id: 'id',
  memberId: 'memberId',
  membershipId: 'membershipId',
  branchId: 'branchId',
  currency: 'currency',
  note: 'note',
  createdByUserId: 'createdByUserId',
  deletedByUserId: 'deletedByUserId',
  voidReason: 'voidReason'
};

exports.Prisma.MembershipPlanOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  branchId: 'branchId',
  description: 'description'
};

exports.Prisma.MemberMembershipOrderByRelevanceFieldEnum = {
  id: 'id',
  memberId: 'memberId',
  planId: 'planId',
  branchId: 'branchId',
  cancelReason: 'cancelReason',
  createdByUserId: 'createdByUserId'
};

exports.Prisma.TagOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  color: 'color'
};

exports.Prisma.MemberTagOrderByRelevanceFieldEnum = {
  memberId: 'memberId',
  tagId: 'tagId'
};

exports.Prisma.MemberNoteOrderByRelevanceFieldEnum = {
  id: 'id',
  memberId: 'memberId',
  createdByUserId: 'createdByUserId',
  note: 'note'
};

exports.Prisma.MemberFlagOrderByRelevanceFieldEnum = {
  id: 'id',
  memberId: 'memberId',
  createdByUserId: 'createdByUserId',
  flag: 'flag',
  description: 'description'
};

exports.Prisma.MediaOrderByRelevanceFieldEnum = {
  id: 'id',
  memberId: 'memberId',
  branchId: 'branchId',
  kind: 'kind',
  uri: 'uri',
  mimeType: 'mimeType'
};

exports.Prisma.AppSettingOrderByRelevanceFieldEnum = {
  branchId: 'branchId',
  key: 'key',
  value: 'value'
};

exports.Prisma.SitePageOrderByRelevanceFieldEnum = {
  id: 'id',
  slug: 'slug',
  title: 'title',
  contentMarkdown: 'contentMarkdown'
};

exports.Prisma.OutboxEventOrderByRelevanceFieldEnum = {
  id: 'id',
  type: 'type',
  idempotencyKey: 'idempotencyKey',
  lastError: 'lastError'
};

exports.Prisma.ProcessedEventOrderByRelevanceFieldEnum = {
  id: 'id',
  idempotencyKey: 'idempotencyKey',
  eventId: 'eventId',
  eventType: 'eventType',
  deviceId: 'deviceId',
  gymId: 'gymId'
};
exports.LegacyUserRole = exports.$Enums.LegacyUserRole = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  STAFF: 'STAFF',
  FRONTDESK: 'FRONTDESK'
};

exports.MemberStatus = exports.$Enums.MemberStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
};

exports.AttendanceSource = exports.$Enums.AttendanceSource = {
  MANUAL: 'MANUAL',
  AUTO: 'AUTO'
};

exports.PaymentMethod = exports.$Enums.PaymentMethod = {
  CASH: 'CASH',
  CARD: 'CARD',
  TRANSFER: 'TRANSFER',
  OTHER: 'OTHER'
};

exports.PaymentStatus = exports.$Enums.PaymentStatus = {
  PAID: 'PAID',
  VOID: 'VOID',
  REFUNDED: 'REFUNDED'
};

exports.OutboxStatus = exports.$Enums.OutboxStatus = {
  PENDING: 'PENDING',
  SENDING: 'SENDING',
  ACKED: 'ACKED',
  FAILED: 'FAILED'
};

exports.ProcessedEventStatus = exports.$Enums.ProcessedEventStatus = {
  ACKED: 'ACKED',
  REJECTED: 'REJECTED'
};

exports.Prisma.ModelName = {
  User: 'User',
  Role: 'Role',
  Permission: 'Permission',
  UserRole: 'UserRole',
  RolePermission: 'RolePermission',
  LoginHistory: 'LoginHistory',
  AuditLog: 'AuditLog',
  Session: 'Session',
  Branch: 'Branch',
  PersonalTrainer: 'PersonalTrainer',
  Member: 'Member',
  Attendance: 'Attendance',
  Payment: 'Payment',
  MembershipPlan: 'MembershipPlan',
  MemberMembership: 'MemberMembership',
  Tag: 'Tag',
  MemberTag: 'MemberTag',
  MemberNote: 'MemberNote',
  MemberFlag: 'MemberFlag',
  Media: 'Media',
  AppSetting: 'AppSetting',
  SitePage: 'SitePage',
  OutboxEvent: 'OutboxEvent',
  ProcessedEvent: 'ProcessedEvent'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
